version: "3"


services:
  spring-app:
    build:
      context: .
      dockerfile: app.dockerfile
    container_name: security
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/demo_security
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  db:
    build:
      context: .
      dockerfile: postgres.dockerfile
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      LC_COLLATE: 'ru_RU.UTF-8'
      LC_CTYPE: 'ru_RU.UTF-8'
    ports:
      - "5432:5432"

#  pgadmin:
#    container_name: pgadmin
#    image: "dpage/pgadmin4"
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: admin
#      PGADMIN_LISTEN_PORT: 80
#    ports:
#      - "8282:80"
#    depends_on:
#      - db
#    links:
#      - postgres